import type { ParticleProject } from '@/types/particle';

export const demoProject: ParticleProject = {
  version: '1.0.0',
  duration: 45,
  emitters: [
    {
      id: 'demo-rose-1',
      type: 'rose-petal',
      name: '玫瑰瓣飘落',
      startTime: 0,
      endTime: 45,
      track: 0,
      config: {
        density: 180,
        windSpeed: 0.4,
        windDirection: 30,
        size: 1.3,
        color: '#e8b4b8',
        opacity: 0.9,
        speed: 1.2,
        spread: 10,
        glow: 0.2,
        rotationSpeed: 1.2,
      },
    },
    {
      id: 'demo-gold-1',
      type: 'gold-dust',
      name: '金粉闪烁',
      startTime: 5,
      endTime: 40,
      track: 1,
      config: {
        density: 400,
        windSpeed: 0.2,
        windDirection: 90,
        size: 0.35,
        color: '#d4a574',
        opacity: 0.8,
        speed: 0.6,
        spread: 12,
        glow: 1.4,
        rotationSpeed: 0.4,
      },
    },
    {
      id: 'demo-heart-1',
      type: 'heart-glow',
      name: '心形光点',
      startTime: 10,
      endTime: 35,
      track: 2,
      config: {
        density: 60,
        windSpeed: 0,
        windDirection: 0,
        size: 1.8,
        color: '#ff6b8a',
        opacity: 1,
        speed: 0.4,
        spread: 6,
        glow: 2,
        rotationSpeed: 0,
      },
    },
    {
      id: 'demo-firefly-1',
      type: 'firefly',
      name: '萤火虫',
      startTime: 15,
      endTime: 45,
      track: 3,
      config: {
        density: 100,
        windSpeed: 0.15,
        windDirection: 200,
        size: 0.5,
        color: '#ffeb99',
        opacity: 0.9,
        speed: 0.5,
        spread: 8,
        glow: 1.6,
        rotationSpeed: 0,
      },
    },
    {
      id: 'demo-star-1',
      type: 'star-rain',
      name: '星光雨',
      startTime: 30,
      endTime: 45,
      track: 4,
      config: {
        density: 250,
        windSpeed: 0.1,
        windDirection: 270,
        size: 0.3,
        color: '#ffffff',
        opacity: 0.9,
        speed: 2.5,
        spread: 15,
        glow: 1,
        rotationSpeed: 0.2,
      },
    },
  ],
};
